version: "2"
services:

  frontend:
    build: ./../images/node
    volumes:
      - ./../../frontend/:/app
    ports:
      - 3000:3000

  sphinx:
    build: ./../images/node-sphinx
    volumes:
      - ./../../documentation/:/app
    ports:
      - 8888:8888

  backend:
    build: ./../images/node
    volumes:
      - ./../../backend/:/app
    ports:
      - 4000:4000
    depends_on:
      - "sql-server"

  # sql-server:
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_SA_PASSWORD=Appelgebak123
  #   ports:
  #     - '1433:1433'
  #   volumes:
  #     - ./../../dbdata:/var/opt/mssql
  #   image: microsoft/mssql-server-linux:2017-latest
  
  sql-server:
    environment:
      - MYSQL_ROOT_PASSWORD=Appelgebak123
      - MYSQL_DATABASE=database_development
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=Appelgebak123
    volumes:
      - ./../../dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    image: mysql:latest
    